# Generated by Django 5.0.1 on 2024-02-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_buyer_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervehicle',
            name='status',
            field=models.CharField(choices=[('0', 'cancelled'), ('1', 'placed'), ('2', 'shipped'), ('3', 'delivered')], default='1', max_length=1),
        ),
    ]
