# Generated by Django 5.0.1 on 2024-02-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_alter_ordervehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('semester', models.IntegerField(default=3)),
                ('personal_page', models.URLField()),
            ],
        ),
    ]
